config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "services#index"
  resources :services
  resources :citas


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cita.rb
class Cita < ApplicationRecord
  self.table_name = "citas"
  belongs_to :user
  belongs_to :service
end

app/models/service.rb
class Service <ApplicationRecord
  has_one_attached :picture
  has_many :citas
  has_many :users, through: :citas


end

app/models/user.rb
class User < ApplicationRecord
  has_many :citas
  has_many :services, through: :citas

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/citas_controller.rb
class CitasController < ApplicationController
  def create
    # service = Service.find(params[:service_id])
    # current_user.services << service
    # ultima_cita = current_user.citas.last
    # ultima_cita.update(date: params[:date])
    ultima_cita = Cita.create(date: params[:date], user_id: current_user.id, service_id: params[:service_id])
    redirect_to "/citas/#{ultima_cita.id}"
  end

  def update
    cita=Cita.find(params[:id])
    cita.update(cita_params)
    redirect_to cita
  end
  def new
    @cita=Cita.new
  end


  def show
    @cita=Cita.find(params[:id])
  end
  def service_params
    params.require(:cita).permit(:name, :date)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services=Service.all
  end

  def new
  @services=Service.new
  end

  def create
    service = Service.new(service_params)
    service.save

    redirect_to service_path(service)
  end

  def show
    @service= Service.find(params[:id])
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    @service.update(service_params)

    redirect_to posts_path
  end

  def destroy
    Service.find(params["id"]).destroy
    redirect_to service_path
  end

  def perfil
  end

  private
  def service_params
    params.require(:service).permit(:descripcion_servicio, :name, :picture, :date)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user=User.all
  end

  def new
  @user=User.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/citas/show.html.erb


<%= @cita.service.name%>
<%= @cita.date.strftime("%m/%d/%Y") rescue nil%>
<%= @cita.user.email%>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Elical Services</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <p> ELECTRICAL>
        <% if user_signed_in? %>
          <p class="navbar-text pull-right">
          <nav class ="navbar navbar-light bg-light">
          <a class="navbar-brand" href="#">

          ElictricalServices</a>
          Logged in as <strong><%= current_user.email %></strong>
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          </nav>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
          </p>
        </p>

      <ul class="nav">
        <li class="active"><%= link_to "HOME", root_path %></li>
      </ul>
    <%= yield %>
  </body>
</html>

app/views/services/edit.html.erb
<%= form_for @service do |f| %>
  <div>
    <label> fecha:</label>
    Fecha: <%= f.text_area :caption %>
  </div>

app/views/services/index.html.erb
<h1> Electrical Service</h1>

<h2> Quienes somos?</h2>
<h3>Somos una empresa que brinda servicios en lineas EnergizadasyMantenimiento, brindando confianza y seguridad a nuestros clientes con innovacion y vanguardia. </h3>
<h2> Que hacemos?</h2>
<h3>Brindamos soluciones para el desarrollo confiable y eficiente de monitoreo de calidad de potencia y energía, pruebas en equipos de subestaciones eléctricas, sistemas industriales y los más avanzados sistemas de protección, control y transferencia de sistemas de potencia.</h3>
<h2> Mision </h2>
<h3>Ser la empresa líder a nivel nacional e incursionar en el mercado latinoamericano con innovación y crecimiento constante</h3>

<h2><%= link_to "new service", new_service_path %></h2>

<% @services.each do |service| %>
  <% if service.picture.attached? %>
    <%= link_to(image_tag(service.picture, height:200), "/services/#{service.id}") %><br><br><br>

  <% end %>
<% end %>

app/views/services/new.html.erb
<div
  <h1>New_Service</h1>
</div>
  
<%= form_for Service.new do |c| %><br><br>
<label> Name_servicio: <%= c.text_field :name %><br/></label><br>
descripcion_servicio: <%= c.text_field :descripcion_servicio %><br/>

<label>picture:</label>
<%= c.file_field :picture %>
<%= c.submit %>
<% end %>

app/views/services/show.html.erb
<div><h1><%= @service.name %></h1></div>
<div><h2><%= @service.descripcion_servicio %></h2></div>

<%= image_tag @service.picture , height:500  if @service.picture.attached? %>

<%= button_to "Comprar", citas_path, params: {service_id: @service.id} %>
<%= form_with(url: "/citas", method: "post") do |f| %>
  date:<%= f.date_field :date %>
  <%= f.hidden_field :service_id, value: @service.id%>
  <%= f.submit %>

<%end%>

<h3>Menu</h3>
<%= link_to "Edit", edit_service_path(@service) %><br>
<%= link_to "Delete", service_path(@service),
            method: :delete,
            data: {confirm: "Are you sure"}%><br>

<%=link_to "All service", services_path %>